name: CI

on:
  push:
  pull_request:
    types: [opened, edited, reopened, synchronize]


jobs:

  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint main-cookbooks
      run: |
        cd provisioners/chef_solo
        docker-compose up --exit-code-from lint lint

  update:
    needs: [verify]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install vendor-cookbooks
      run: |
        cd provisioners/chef_solo
        docker-compose up --exit-code-from install install

    # only on develop branch
    - name: Commit files
      run: |
        BRANCH_NAME=$(echo ${GITHUB_REF} | sed -e "s/refs\/heads\///g")
        echo "::set-env name=BRANCH_NAME::$BRANCH_NAME"

        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "vendor-cookbooks updated from CI" || true # ok if no changes
      if: startsWith(github.ref, 'refs/heads/')

    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH_NAME }}
      if: startsWith(github.ref, 'refs/heads/')
